GET http://localhost:3000/restricted
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlbGVvbGEiLCJpYXQiOjE2NTQ1MjczMTB9.GXjTNVwCsRdo0WNqUBV_0gNEvJSvbYLGOVFemaHhAN8

{
    "username": "deleola",
    "email":"leoolapastries@yahoo.com",
    "password":"roseg"
}


#